[project]
name = "ptb-monkey-patching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "python-telegram-bot>=21.6",
]
